version: '3.1'

services:
- name: Build and push Docker images
  uses: docker/build-push-action@v2.9.0
  gpgen:
    container_name: FakeGreenPassGenerator
    build: ./FakeGreenPassGenerator
    volumes:
      - "./FakeGreenPassGenerator:/app"
  # qrcodegen:
  #   container_name: QRCodeGen
  #   build: ./QRCodeGenerator
  #   volumes:
  #     - "./QRCodeGenerator:/app"

